
const INIT_CHECKLIST_START =  'wbonline/chcklistSettings/INIT_CHECKLIST_START';
const INIT_CHECKLIST_SUCCESS =  'wbonline/chcklistSettings/INIT_CHECKLIST_SUCCESS';
const INIT_CHECKLIST_ERROR =  'wbonline/chcklistSettings/INIT_CHECKLIST_ERROR';

const CHANGE_CHECKLIST_CATEGORY =  'wbonline/chcklistSettings/CHANGE_CHECKLIST_CATEGORY';
const CHANGE_CHECKLIST_SUB_CATEGORY =  'wbonline/chcklistSettings/CHANGE_CHECKLIST_SUB_CATEGORY';

const LOAD_CHECKLIST_ITEM_START =  'wbonline/chcklistSettings/LOAD_CHECKLIST_ITEM_START';
const LOAD_CHECKLIST_ITEM_SUCCESS =  'wbonline/chcklistSettings/LOAD_CHECKLIST_ITEM_SUCCESS';
const LOAD_CHECKLIST_ITEM_ERROR =  'wbonline/chcklistSettings/LOAD_CHECKLIST_ITEM_ERROR';

const UPDATE_CHECKLIST_ITEM_START =  'wbonline/chcklistSettings/UPDATE_CHECKLIST_ITEM_START';
const UPDATE_CHECKLIST_ITEM_SUCCESS =  'wbonline/chcklistSettings/UPDATE_CHECKLIST_ITEM_SUCCESS';
const UPDATE_CHECKLIST_ITEM_ERROR =  'wbonline/chcklistSettings/UPDATE_CHECKLIST_ITEM_ERROR';

const UPDATE_CHECKLIST_NEW_ITEM =  'wbonline/chcklistSettings/UPDATE_CHECKLIST_NEW_ITEM';
const ADD_CHECKLIST_NEW_ITEM_START =  'wbonline/chcklistSettings/ADD_CHECKLIST_NEW_ITEM_START';
const ADD_CHECKLIST_NEW_ITEM_SUCCESS =  'wbonline/chcklistSettings/ADD_CHECKLIST_NEW_ITEM_SUCCESS';
const ADD_CHECKLIST_NEW_ITEM_ERROR =  'wbonline/chcklistSettings/ADD_CHECKLIST_NEW_ITEM_ERROR';

const ADD_CHECKLIST_NEW_SUB_CATEGORY_START =  'wbonline/chcklistSettings/ADD_CHECKLIST_NEW_SUB_CATEGORY_START';
const ADD_CHECKLIST_NEW_SUB_CATEGORY_SUCCESS =  'wbonline/chcklistSettings/ADD_CHECKLIST_NEW_SUB_CATEGORY_SUCCESS';
const ADD_CHECKLIST_NEW_SUB_CATEGORY_ERROR =  'wbonline/chcklistSettings/ADD_CHECKLIST_NEW_SUB_CATEGORY_ERROR';

const CHECK_CHECKLIST_ALL_ITEMS = 'wbonline/chcklistSettings/CHECK_CHECKLIST_ALL_ITEMS';
const CHECK_CHECKLIST_ITEM = 'wbonline/chcklistSettings/CHECK_CHECKLIST_ITEM';


const REMOVE_CHECKLIST_ITEMS_REQUEST = 'wbonline/chcklistSettings/REMOVE_CHECKLIST_ITEMS_REQUEST';
const REMOVE_CHECKLIST_ITEMS_START = 'wbonline/chcklistSettings/REMOVE_CHECKLIST_ITEMS_START';
const REMOVE_CHECKLIST_ITEMS_SUCCESS = 'wbonline/chcklistSettings/REMOVE_CHECKLIST_ITEMS_SUCCESS';
const REMOVE_CHECKLIST_ITEMS_ERROR = 'wbonline/chcklistSettings/REMOVE_CHECKLIST_ITEMS_ERROR';

const ASSIGN_CHECKLIST_ITEM_START = 'wbonline/chcklistSettings/ASSIGN_CHECKLIST_ITEM_START';
const ASSIGN_CHECKLIST_ITEM_SUCCESS = 'wbonline/chcklistSettings/ASSIGN_CHECKLIST_ITEM_SUCCESS';
const ASSIGN_CHECKLIST_ITEM_ERROR = 'wbonline/chcklistSettings/ASSIGN_CHECKLIST_ITEM_ERROR';

const LOAD_CHECKLIST_ITEM_TASK_START = 'wbonline/chcklistSettings/LOAD_CHECKLIST_ITEM_TASK_START';
const LOAD_CHECKLIST_ITEM_TASK_SUCCESS = 'wbonline/chcklistSettings/LOAD_CHECKLIST_ITEM_TASK_SUCCESS';
const LOAD_CHECKLIST_ITEM_TASK_ERROR = 'wbonline/chcklistSettings/LOAD_CHECKLIST_ITEM_TASK_ERROR';

const ADD_CHECKLIST_ITEM_TASK_START = 'wbonline/chcklistSettings/ADD_CHECKLIST_ITEM_TASK_START';
const ADD_CHECKLIST_ITEM_TASK_SUCCESS = 'wbonline/chcklistSettings/ADD_CHECKLIST_ITEM_TASK_SUCCESS';
const ADD_CHECKLIST_ITEM_TASK_ERROR = 'wbonline/chcklistSettings/ADD_CHECKLIST_ITEM_TASK_ERROR';

const UPDATE_CHECKLIST_SUB_TASK_ITEM_START =  'wbonline/chcklistSettings/UPDATE_CHECKLIST_SUB_TASK_ITEM_START';
const UPDATE_CHECKLIST_SUB_TASK_ITEM_SUCCESS =  'wbonline/chcklistSettings/UPDATE_CHECKLIST_SUB_TASK_ITEM_SUCCESS';
const UPDATE_CHECKLIST_SUB_TASK_ITEM_ERROR =  'wbonline/chcklistSettings/UPDATE_CHECKLIST_SUB_TASK_ITEM_ERROR';

const REMOVE_CHECKLIST_SUB_TASK_ITEM_START =  'wbonline/chcklistSettings/REMOVE_CHECKLIST_SUB_TASK_ITEM_START';
const REMOVE_CHECKLIST_SUB_TASK_ITEM_SUCCESS =  'wbonline/chcklistSettings/REMOVE_CHECKLIST_SUB_TASK_ITEM_SUCCESS';
const REMOVE_CHECKLIST_SUB_TASK_ITEM_ERROR =  'wbonline/chcklistSettings/REMOVE_CHECKLIST_SUB_TASK_ITEM_ERROR';

const SORT_CHECKLIST_SUB_TASK_ITEMS_START =  'wbonline/chcklistSettings/SORT_CHECKLIST_SUB_TASK_ITEMS_START';
const SORT_CHECKLIST_SUB_TASK_ITEMS_SUCCESS =  'wbonline/chcklistSettings/SORT_CHECKLIST_SUB_TASK_ITEMS_SUCCESS';
const SORT_CHECKLIST_SUB_TASK_ITEMS_ERROR =  'wbonline/chcklistSettings/SORT_CHECKLIST_SUB_TASK_ITEMS_ERROR';

const SORT_CHECKLIST_ITEMS_START =  'wbonline/chcklistSettings/SORT_CHECKLIST_ITEMS_START';
const SORT_CHECKLIST_ITEMS_SUCCESS =  'wbonline/chcklistSettings/SORT_CHECKLIST_ITEMS_SUCCESS';
const SORT_CHECKLIST_ITEMS_ERROR =  'wbonline/chcklistSettings/SORT_CHECKLIST_ITEMS_ERROR';

const REMOVE_CHECKLIST_SUB_TASK_ITEMS_START =  'wbonline/chcklistSettings/REMOVE_CHECKLIST_SUB_TASK_ITEMS_START';
const REMOVE_CHECKLIST_SUB_TASK_ITEMS_SUCCESS =  'wbonline/chcklistSettings/REMOVE_CHECKLIST_SUB_TASK_ITEMS_SUCCESS';
const REMOVE_CHECKLIST_SUB_TASK_ITEMS_ERROR =  'wbonline/chcklistSettings/REMOVE_CHECKLIST_SUB_TASK_ITEMS_ERROR';

const CHECK_CHECKLIST_SUB_TASK_ITEM =  'wbonline/chcklistSettings/CHECK_CHECKLIST_SUB_TASK_ITEM';


export default {
    INIT_CHECKLIST_START,
    INIT_CHECKLIST_SUCCESS,
    INIT_CHECKLIST_ERROR,

    CHANGE_CHECKLIST_CATEGORY,
    CHANGE_CHECKLIST_SUB_CATEGORY,

    LOAD_CHECKLIST_ITEM_START,
    LOAD_CHECKLIST_ITEM_SUCCESS,
    LOAD_CHECKLIST_ITEM_ERROR,

    UPDATE_CHECKLIST_ITEM_START,
    UPDATE_CHECKLIST_ITEM_SUCCESS,
    UPDATE_CHECKLIST_ITEM_ERROR,

    UPDATE_CHECKLIST_NEW_ITEM,
    ADD_CHECKLIST_NEW_ITEM_START,
    ADD_CHECKLIST_NEW_ITEM_SUCCESS,
    ADD_CHECKLIST_NEW_ITEM_ERROR,

    ADD_CHECKLIST_NEW_SUB_CATEGORY_START,
    ADD_CHECKLIST_NEW_SUB_CATEGORY_SUCCESS,
    ADD_CHECKLIST_NEW_SUB_CATEGORY_ERROR,

    CHECK_CHECKLIST_ALL_ITEMS,
    CHECK_CHECKLIST_ITEM,

    REMOVE_CHECKLIST_ITEMS_REQUEST,
    REMOVE_CHECKLIST_ITEMS_START,
    REMOVE_CHECKLIST_ITEMS_SUCCESS,
    REMOVE_CHECKLIST_ITEMS_ERROR,

    ASSIGN_CHECKLIST_ITEM_START,
    ASSIGN_CHECKLIST_ITEM_SUCCESS,
    ASSIGN_CHECKLIST_ITEM_ERROR,

    LOAD_CHECKLIST_ITEM_TASK_START,
    LOAD_CHECKLIST_ITEM_TASK_SUCCESS,
    LOAD_CHECKLIST_ITEM_TASK_ERROR,

    ADD_CHECKLIST_ITEM_TASK_START,
    ADD_CHECKLIST_ITEM_TASK_SUCCESS,
    ADD_CHECKLIST_ITEM_TASK_ERROR,

    UPDATE_CHECKLIST_SUB_TASK_ITEM_START,
    UPDATE_CHECKLIST_SUB_TASK_ITEM_SUCCESS,
    UPDATE_CHECKLIST_SUB_TASK_ITEM_ERROR,

    REMOVE_CHECKLIST_SUB_TASK_ITEM_START,
    REMOVE_CHECKLIST_SUB_TASK_ITEM_SUCCESS,
    REMOVE_CHECKLIST_SUB_TASK_ITEM_ERROR,

    SORT_CHECKLIST_SUB_TASK_ITEMS_START,
    SORT_CHECKLIST_SUB_TASK_ITEMS_SUCCESS,
    SORT_CHECKLIST_SUB_TASK_ITEMS_ERROR,

    SORT_CHECKLIST_ITEMS_START,
    SORT_CHECKLIST_ITEMS_SUCCESS,
    SORT_CHECKLIST_ITEMS_ERROR,

    REMOVE_CHECKLIST_SUB_TASK_ITEMS_START,
    REMOVE_CHECKLIST_SUB_TASK_ITEMS_SUCCESS,
    REMOVE_CHECKLIST_SUB_TASK_ITEMS_ERROR,

    CHECK_CHECKLIST_SUB_TASK_ITEM
};